"""initial state

Revision ID: 07d5a1ce4e29
Revises: 
Create Date: 2020-01-25 15:00:45.144060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d5a1ce4e29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('free', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Text(), nullable=False),
    sa.Column('time', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('teachers_to_goals',
    sa.Column('teachers', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goals'], ['goals.goal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teachers'], ['teachers.teacher_id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers_to_goals')
    op.drop_table('requests')
    op.drop_table('bookings')
    op.drop_table('teachers')
    op.drop_table('goals')
    # ### end Alembic commands ###
